### ISSUE TITLE
SomeClass.only( :some_non_carrierwave_field )

### ISSUE THREAD

**Issue by davingee** [carrierwaveuploader/carrierwave-mongoid#135]
When I try to use .only found on http://mongoid.org/en/origin/docs/options.html, 
If I do
  Tester.all.only(:created_at ).as_json
I get 
Overwriting existing field test_image in class Tester.
  MOPED: 127.0.0.1:27017 QUERY        database=meta_6_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"created_at"=>1, "_id"=>1} runtime: 3.0782ms
ActiveModel::MissingAttributeError: Missing attribute: 'test_image'.
from /Users/scott/.rvm/gems/ruby-2.1.3@api_on_the_fly/bundler/gems/mongoid-a4a4b7391e77/lib/mongoid/attributes.rb:97:in `read_attribute'

if I do 
  Tester.all.only(:created_at, :test_image).as_json
it works and I get the array back with only those three columns

=> [{"tester"=>{"created_at"=>Mon, 01 Dec 2014 06:52:27 UTC +00:00, "test_image"=>{"url"=>nil, :thumb=>{"url"=>nil}}}},

**Comment by davingee** [comment]
Back at it!
Here is the backtrace

When I do not mount the uploader I can do Tester.only(:created_at).as_json and it works
Tester.only(:created_at).as_json
  MOPED: 127.0.0.1:27017 QUERY        database=meta_8_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"created_at"=>1} runtime: 0.8023ms
 => [{"tester"=>{"created_at"=>Mon, 25 May 2015 02:27:45 UTC +00:00}}, {"tester"=>{"created_at"=>Mon, 25 May 2015 02:27:54 UTC +00:00}}, {"tester"=>{"created_at"=>Mon, 25 May 2015 02:27:55 UTC +00:00}}, {"tester"=>{"created_at"=>Mon, 25 May 2015 02:27:56 UTC +00:00}}] 

## works fine when I supply only with id and test_image

Tester.only([ :id, :created_at, :test_image]).as_json
  MOPED: 127.0.0.1:27017 QUERY        database=meta_8_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"_id"=>1, "created_at"=>1, "test_image"=>1} runtime: 1.2381ms
 => [{"tester"=>{"_id"=>BSON::ObjectId('556288a1446176922a010000'), "created_at"=>Mon, 25 May 2015 02:27:45 UTC +00:00, "test_image"=>{"url"=>"/public/uploads/meta_8_development/tester/556288a1446176922a010000/image.jpg"}}}, {"tester"=>{"_id"=>BSON::ObjectId('556288aa446176922a020000'), "created_at"=>Mon, 25 May 2015 02:27:54 UTC +00:00, "test_image"=>{"url"=>"/public/uploads/meta_8_development/tester/556288aa446176922a020000/image.jpg"}}}, {"tester"=>{"_id"=>BSON::ObjectId('556288ab446176922a030000'), "created_at"=>Mon, 25 May 2015 02:27:55 UTC +00:00, "test_image"=>{"url"=>"/public/uploads/meta_8_development/tester/556288ab446176922a030000/image.jpg"}}}, {"tester"=>{"_id"=>BSON::ObjectId('556288ac446176922a040000'), "created_at"=>Mon, 25 May 2015 02:27:56 UTC +00:00, "test_image"=>{"url"=>"/public/uploads/meta_8_development/tester/556288ac446176922a040000/image.jpg"}}}] 

 ## only with out id not working

Tester.only([ :created_at, :test_image]).as_json
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 0.8881ms
  MOPED: 127.0.0.1:27017 QUERY        database=meta_8_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"created_at"=>1, "test_image"=>1} runtime: 0.8941ms
ActiveModel::MissingAttributeError: Missing attribute: '_id'.
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/attributes.rb:97:in `read_attribute'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/fields.rb:409:in `block (2 levels) in create_field_getter'
  from /Users/scott/rails/api_on_the_fly_it/api/app/uploaders/attachment_uploader.rb:16:in `store_dir'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:43:in `store_path'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/storage/file.rb:50:in `retrieve!'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:95:in `block in retrieve_from_store!'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:94:in `retrieve_from_store!'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:323:in `uploader'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:100:in `block in serializable_hash'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:98:in `each'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:98:in `serializable_hash'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activemodel-4.0.2/lib/active_model/serializers/json.rb:97:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:58:in `block in as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:81:in `check_for_circular_references'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:57:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `block in as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `map'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/criteria.rb:60:in `as_json'
  from (irb):20
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
  from bin/rails:4:in `require'


  ## only(:created_at) is still looking for test_image

  Tester.only(:created_at).as_json
  MOPED: 127.0.0.1:27017 QUERY        database=meta_8_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"created_at"=>1} runtime: 1.2102ms
ActiveModel::MissingAttributeError: Missing attribute: 'test_image'.
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/attributes.rb:97:in `read_attribute'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:318:in `identifier'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:323:in `uploader'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:100:in `block in serializable_hash'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:98:in `each'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:98:in `serializable_hash'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activemodel-4.0.2/lib/active_model/serializers/json.rb:97:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:58:in `block in as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:81:in `check_for_circular_references'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:57:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `block in as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `map'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/criteria.rb:60:in `as_json'
  from (irb):21
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'2.1.5 :022 >
