### ISSUE TITLE
Cant query using only unless  id and the image_field_name are within only()

### ISSUE THREAD

**Issue by davingee** [carrierwaveuploader/carrierwave-mongoid#147]
Here is the backtrace

When I do not mount the uploader I can do Tester.only(:created_at).as_json and it works
````
Tester.only(:created_at).as_json
  MOPED: 127.0.0.1:27017 QUERY        database=meta_8_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"created_at"=>1} runtime: 0.8023ms
 => [{"tester"=>{"created_at"=>Mon, 25 May 2015 02:27:45 UTC +00:00}}, {"tester"=>{"created_at"=>Mon, 25 May 2015 02:27:54 UTC +00:00}}, {"tester"=>{"created_at"=>Mon, 25 May 2015 02:27:55 UTC +00:00}}, {"tester"=>{"created_at"=>Mon, 25 May 2015 02:27:56 UTC +00:00}}] 
````
## works fine when I supply only with id and test_image
````
Tester.only([ :id, :created_at, :test_image]).as_json
  MOPED: 127.0.0.1:27017 QUERY        database=meta_8_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"_id"=>1, "created_at"=>1, "test_image"=>1} runtime: 1.2381ms
 => [{"tester"=>{"_id"=>BSON::ObjectId('556288a1446176922a010000'), "created_at"=>Mon, 25 May 2015 02:27:45 UTC +00:00, "test_image"=>{"url"=>"/public/uploads/meta_8_development/tester/556288a1446176922a010000/image.jpg"}}}, {"tester"=>{"_id"=>BSON::ObjectId('556288aa446176922a020000'), "created_at"=>Mon, 25 May 2015 02:27:54 UTC +00:00, "test_image"=>{"url"=>"/public/uploads/meta_8_development/tester/556288aa446176922a020000/image.jpg"}}}, {"tester"=>{"_id"=>BSON::ObjectId('556288ab446176922a030000'), "created_at"=>Mon, 25 May 2015 02:27:55 UTC +00:00, "test_image"=>{"url"=>"/public/uploads/meta_8_development/tester/556288ab446176922a030000/image.jpg"}}}, {"tester"=>{"_id"=>BSON::ObjectId('556288ac446176922a040000'), "created_at"=>Mon, 25 May 2015 02:27:56 UTC +00:00, "test_image"=>{"url"=>"/public/uploads/meta_8_development/tester/556288ac446176922a040000/image.jpg"}}}] 
````
 ## only with out id not working
````
Tester.only([ :created_at, :test_image]).as_json
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 0.8881ms
  MOPED: 127.0.0.1:27017 QUERY        database=meta_8_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"created_at"=>1, "test_image"=>1} runtime: 0.8941ms
ActiveModel::MissingAttributeError: Missing attribute: '_id'.
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/attributes.rb:97:in `read_attribute'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/fields.rb:409:in `block (2 levels) in create_field_getter'
  from /Users/scott/rails/api_on_the_fly_it/api/app/uploaders/attachment_uploader.rb:16:in `store_dir'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:43:in `store_path'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/storage/file.rb:50:in `retrieve!'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:95:in `block in retrieve_from_store!'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:94:in `retrieve_from_store!'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:323:in `uploader'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:100:in `block in serializable_hash'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:98:in `each'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:98:in `serializable_hash'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activemodel-4.0.2/lib/active_model/serializers/json.rb:97:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:58:in `block in as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:81:in `check_for_circular_references'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:57:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `block in as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `map'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/criteria.rb:60:in `as_json'
  from (irb):20
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
  from bin/rails:4:in `require'

````
  ## only(:created_at) is still looking for test_image
````
  Tester.only(:created_at).as_json
  MOPED: 127.0.0.1:27017 QUERY        database=meta_8_development collection=testers selector={} flags=[] limit=0 skip=0 batch_size=nil fields={"created_at"=>1} runtime: 1.2102ms
ActiveModel::MissingAttributeError: Missing attribute: 'test_image'.
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/attributes.rb:97:in `read_attribute'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:318:in `identifier'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:323:in `uploader'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:100:in `block in serializable_hash'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:98:in `each'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/carrierwave-mongoid-ee7d38e353df/lib/carrierwave/mongoid.rb:98:in `serializable_hash'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activemodel-4.0.2/lib/active_model/serializers/json.rb:97:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:58:in `block in as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:81:in `check_for_circular_references'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:57:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `block in as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `map'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/activesupport-4.0.2/lib/active_support/json/encoding.rb:270:in `as_json'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/bundler/gems/mongoid-e1db083b2a5f/lib/mongoid/criteria.rb:60:in `as_json'
  from (irb):21
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
  from /Users/scott/.rvm/gems/ruby-2.1.5@api_on_the_fly/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'2.1.5 :022 > 
````

**Comment by rmm5t** [comment]
Please reformat and rephrase your questions and statements thoughtfully. This issue is almost completely incoherent otherwise.

**Comment by davingee** [comment]
Sorry about that.
I am trying to use Model.only.
when I mount the uploader I can not use only without including the attachment_field_name ex: .only( [ :test_image, :created_at ] )

I think the issue is that I am connecting to the database dynamically.

session = Moped::Session.new( ["127.0.0.1:27017"] )
session.use( 'meta_1_test' )
session.login( 'username', 'password' )
Mongoid::Threaded.sessions[ 'meta_1_test' ] = session
Mongoid::Threaded.database_override = meta_1_test

def serializable_hash(options=nil) <-- your code. options is always nil 
  hash = {}
  except = options && options[:except] && Array.wrap(options[:except]).map(&:to_s)
  only   = options && options[:only]   && Array.wrap(options[:only]).map(&:to_s)

  self.class.uploaders.each do |column, uploader|
    binding.pry
    if (!only && !except) || (only && only.include?(column.to_s)) || (except && !except.include?(column.to_s))
      hash[column.to_s] = _mounter(column.to_sym).uploader.serializable_hash
    end
  end
  super(options).merge(hash)
end

options is always nil in serializable_hash(options=nil) so it is including it even when when 'only' is being used

any idea's

**Comment by davingee** [comment]
````
require 'carrierwave/mongoid'
class Tester

  include Mongoid::Document
  include Mongoid::Timestamps

  store_in collection:  "testers", database: 'primary'

  mount_uploader        :test_image, AttachmentUploader

  field :test_string,   type: String
  field :test_date,     type: Date
  field :test_time,     type: Time
  field :test_integer,  type: Integer
  field :test_boolean,  type: Boolean
  field :test_float,    type: Float

  def test
    Tester.change_db
    Tester.add_a_row( rows_to_add: 10 )

    ## works
    Tester.all.as_json

    # works
    Tester.only( [ :created_at, :test_image, :_id ] ).as_json

    # breaks
    Tester.only( :created_at ).as_json
  end

  def self.change_db

    db = OpenStruct.new( { 
      password:   '68636193691925610477880992228277995677', 
      user_name:  'foo_bar_com', 
      port:       27017, 
      host:       '127.0.0.1', 
      db_name:    'meta_8_development' 
    } )

    db_hosts_and_ports  = [ "#{ db.host }:#{ db.port }" ]
    db_name                = db.db_name
    db_username         = db.user_name
    db_password          = db.password

    Mongoid.default_session.disconnect
    session = Moped::Session.new( db_hosts_and_ports )
    session.use( db_name )
    session.login( db_username, db_password )
    Mongoid::Threaded.sessions[ db_name ] = session
    Mongoid::Threaded.database_override = db_name
  end

  def self.add_a_row( args = { } )
    ( 0..args.fetch( :rows_to_add, 1 ) ).to_a.each do | n |
      t                        = Tester.new
      t.test_image      = File.open( "#{ Rails.root }/spec/files/image.jpg" )
      t.test_string       = "test_string"
      t.test_date         = Date.today
      t.test_time         = Time.now
      t.test_integer     = 12345
      t.test_boolean   = true
      t.test_float         = 5.5
      t.save
    end
  end

end
````
